MODEL:
  PRETRAIN_HW_RATIO: 2
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'pose_swin_tiny_patch4_window7_224'
  STRIDE_SIZE: [16, 16]

  # 我新加的
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: "pretrained/swin_tiny.pth"

  POSE:
    ENABLE: true              # 第一步打开
    CFG: pose/config_vispredict.py
    CKPT: pretrained/best_coco_AP_epoch_210.pth
    SAVE_VIS: true
    N_KPTS: 17
    FUSE_STAGE: 2             # stage2 对齐较稳
    BRANCH_STAGE: 2           # stage2 之后拆分局部/全局
    FUSION_MODE: mul          # 先用乘性门
    USE_VIS: true
    HM_NORM: sigmoid
    DETACH: true
    SCALE: 1.0

  FREEZE:
    ENABLE: true
    # 冻结策略：先保护主干与姿态网的预训练权重，后续再解冻
    RULES:
      - MODULE: base.swin             # 前 5 个 epoch 冻结整个 Swin 主干
        START_EPOCH: 1
        END_EPOCH: 5
        SET_EVAL: True
      - MODULE: base.pose_predictor   # 前 10 个 epoch 冻结姿态预测器
        START_EPOCH: 1
        END_EPOCH: 10
        SET_EVAL: True


INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST:  [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.0008
  WARMUP_EPOCHS: 20
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'cosine'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 20
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './log/market1501/swin_tiny_pose-mul-test-scale1.0'
